dataset: blender
subset: lego
frame_ids: [9]
data_dir: datasets/nerf_synthetic/
train_dir: models/blender/
result_dir: results/
print_every: 10
num_coarse_samples: 64
num_fine_samples: 128
white_bkgd: true
randomized: false
use_pixel_centers: false

test_name: coarse_single_img
pixel_sampling: random
distributed_render: true
per_sample_gradient: false
use_original_img: false
resample_rays: true
perturbation_R: 0.3
perturbation_t: 0.5
pixel_count: 2048
max_steps: 1200
optimizer: adam
lr_init: 0.02
decay_steps: 1200
decay_rate: 0.6
huber_delta: 0.2
chunk: 2048
clip_grad: 0.05
