dataset: blender
subset: lego
frame_idx: 29
data_dir: datasets/nerf_synthetic/
train_dir: models/blender/
result_dir: results/
print_every: 10
num_coarse_samples: 64
num_fine_samples: 128
white_bkgd: true
use_pixel_centers: true

pixel_sampling: random
distributed_render: true
per_sample_gradient: false
use_original_img: true
perturbation_R: 0.3
perturbation_t: 0.5
pixel_count: 2048
max_steps: 300
optimizer: sgd
lr_init: 0.005
decay_steps: 100
decay_rate: 0.6
huber_delta: 1.
chunk: 2048
clip_grad: 0.
